### ISSUE TITLE
NC200

### ISSUE THREAD

**Issue by Vextil** [reald/nc220#2]
Checked on my NC200 and the only working streams I could find are /stream/getvideo and /stream/getaudio. Just putting this here for anyone trying to find it.

**Comment by vdchuyen** [comment]
Thanks so much, i'm looking for this to get rid of sending to *cloud*.

**Comment by fjvelarde** [comment]
Hey @Vextil how you can embed the stream to a web site? I'm trying to do with your /stream/getvideo but i couldn't .

**Comment by Vextil** [comment]
The feed is a mjpeg stream so you can just do:
`<img src="http://cam_ip:8080/stream/getvideo">`

**Comment by arushk1** [comment]
@Vextil How do I use this to get stream in python?

**Comment by Vextil** [comment]
No idea, to be completely honest.

**Comment by arushk1** [comment]
These are VGA streams right? Know how to get HD stream?

**Comment by reald** [comment]
NC200 and NC220 only support VGA, not HD.
