### ISSUE TITLE
Access to the RTMP server on the device

### ISSUE THREAD

**Issue by ignisf** [reald/nc220#5]
Hello,

I've been toying around with an NC 250.

The RTMP server seems to respond, however I'm not sure what the stream parameters are or if there even is a stream. Binwalking through the firmware and disassembling `/sbin/streamd` did not yield anything obvious.

It would be great if anybody stumbles across a solution for this :)

**Comment by solosoluciones** [comment]
I don't know about the NC250, but this works on the NC220: ffplay rtmp://192.168.1.49:1935/stream/video/h264

**Comment by reald** [comment]
Works for NC220, too. Thanks for solosoluciones for this info.
