### ISSUE TITLE
RSTP or HTTP Streaming with Sound

### ISSUE THREAD

**Issue by nachopro** [reald/nc220#6]
I know that you are an a caritative person, and I know that TP-Link do not answer questions about NC220 device :(

Do you know how to get an Streaming with sound?
The URLs that you talk about in this repo are not working on Version 1.1.12 Build 160321 Rel.27531 :(

The RTSP launches a lot of errors on VLC/ZoneMinder (ES_OUT_RESET_PCR called, Could not convert timestamp 0, etc)

The HTTP Streams with H.264 only hangup the VLC or Browser instance :(

Any observation that you can give me are wellcome!

Thanks for this repo!

**Comment by reald** [comment]
ffplay rtmp://[ipofcamera]:1935/stream/video/h264
